#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
- name: Assign values if IB vCenter action selected
  set_fact:
    vcenter_type: ib
  tags:
    - create_ib_datacenter_create_task
    - create_ib_datacenter_destroy_task

- name: Assign values if OOB vCenter action selected
  set_fact:
    vcenter_type: oob
  tags:
    - create_oob_datacenter_create_task
    - create_oob_datacenter_destroy_task

- name: Create the task to create the datacenter in the IB vCenter
  template: src=../templates/create_datacenter.yml.j2 dest={{ vcenter_role_directory }}/tasks/create_ib_datacenter.yml
  tags:
    - create_ib_datacenter_create_task

- name: Create the task to destroy the datacenter in the IB vCenter
  template: src=../templates/destroy_datacenter.yml.j2 dest={{ vcenter_role_directory }}/tasks/destroy_ib_datacenter.yml
  tags:
    - create_ib_datacenter_destroy_task

- name: Create the task to create the datacenter in the OOB vCenter
  template: src=../templates/create_datacenter.yml.j2 dest={{ vcenter_role_directory }}/tasks/create_oob_datacenter.yml
  tags:
    - create_oob_datacenter_create_task

- name: Create the task to destroy the datacenter in the OOB vCenter
  template: src=../templates/destroy_datacenter.yml.j2 dest={{ vcenter_role_directory }}/tasks/destroy_oob_datacenter.yml
  tags:
    - create_oob_datacenter_destroy_task

- name: Create datacenter in the IB vCenter
  include: create_ib_datacenter.yml
  tags:
    - create_ib_datacenter

- name: Create datacenter in the OOB vCenter
  include: create_oob_datacenter.yml
  tags:
    - create_oob_datacenter

- name: Destroy datacenter in the IB vCenter
  include: destroy_ib_datacenter.yml
  tags:
    - destroy_ib_datacenter

- name: Create datacenter in the OOB vCenter
  include: destroy_oob_datacenter.yml
  tags:
    - destroy_oob_datacenter
