#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
- name: Assign values if OOB vCenter action selected
  set_fact:
    vcenter_type: oob
    vcenter_action: datacenter
  tags:
    - create_oob_datacenter_task

- name: Assign values if IB vCenter action selected
  set_fact:
    vcenter_type: ib
    vcenter_action: datacenter
  tags:
    - create_ib_datacenter_task

- name: Create the actionable task
  template: src=../templates/create_datacenter.yml.j2 dest={{ vcenter_task_directory }}/create_oob_datacenter.yml
  tags:
    - create_oob_datacenter_task

- name: Create Datacenter
  include: create_oob_datacenter.yml
  tags:
    - oob_datacenter

- name: Create VDS and Portgroups
  include: vds_pgs.yml
  tags:
    - vds

- name: Add Hosts to Clusters
  include: addhosts.yml
  tags:
    - addhosts

- name: Configure Hosts
  include: confighosts.yml
  tags:
    - confighosts

- name: Create Host Profiles
  include: hostprofiles.yml
  tags:
    - hostprofile

- name: Apply Host Profiles
  include: applyprofiles.yml
  tags:
    - applyprofile
